% Auto-generated by Data Acquisition Toolbox Analog Input Recorder on 09-Jan-2020 13:58:11
close all; clc; clearvars;

% Create Data Acquisition Session
HETDAQ.s = daq('ni');

%Set the sweep rate.
baudRate = 1.0e6;
HETDAQ.s.Rate = baudRate;

%Input the device ID.
HETDAQ.dev = 'Dev1';

measurementType = 'Voltage';  
%Set up some input values and measurement types.
inputChannelOneID = 'ai0';  %Connects the NIDAC connector AI0 to the matlab code.
outputChannelOneID = 'ao0';
HETDAQ.outputChannelOne = addoutput(HETDAQ.s, HETDAQ.dev, outputChannelOneID, measurementType);

%Add input(to the NIDAQ box-i.e. input from instrument, not computer.) channel one.
HETDAQ.inputChannelOne = addinput(HETDAQ.s, HETDAQ.dev, inputChannelOneID, measurementType); 
HETDAQ.inputChannelOne.TerminalConfig = 'SingleEnded';

%Get the GUI handles and run the program through the GUI handles.
handles = getHETHandles(HETDAQ, baudRate);

